---
- name: Ensure nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable and start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
