---
- name: Ensure IIS is installed
  ansible.windows.win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_features: yes
  register: iis_install

- name: Reboot if IIS was installed
  ansible.windows.win_reboot:
  when: iis_install.changed

- name: Ensure default IIS website is absent
  community.windows.win_iis_website:
    name: "Default Web Site"
    state: absent
